# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FOR(;;)
email: karapanos.dimitris@gmail.com
description: Engineer // Me // Developer
meta: Dimitris Karapanos Engineer Web Developer Full Stack PHP Javascript HTML5 CSS3 AngularJS Yii2 jQuery
about-text: Hello there I'm Dimitris Karapanos</strong>, an Engineer and Web developer enthusiast currently living in Paris, France. I have worked as a full stack developer getting my hands dirty in back end programming (PHP/MySQL/Yii2) and front end engineering (Javascript/AngularJS/jQuery/HTML5/CSS3).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  gpanos

# Collections

collections:
- data


# Build settings
markdown: kramdown
