#-------------------------------------------------------------------------
# Education section 

universities:
- icon: 'University-logo.png'
  name: 'Duth'
  details: '2011-2013'
  text: '<strong>Master Degree</strong> Democritus University of Thrace (UDT), Xanthi, Greece 
         «System Engineering & Management», orientation Energy, Industrial and Environmental Systems Management.
         Departments of Civil Engineering and Electrical Engineering & Computer Engineering of the Democritus University of Thrace 
         in collaboration with the Department of Business Management & Administration of the University of Macedonia'
  logo: 'duth.png'
- icon: 'University-logo.png'
  name: 'IPMA'
  details: '2011-2012'
  text: '<strong>Certified Project Management Associate</strong> (IPMA), level D (Certificate Number: 201207002),
         by PMG Cert, the Certification Body of PM-Greece (Network of Project Managers in Greece) using the Regulations of PMGCert and the ICB Version 3.0
         as validated by the International Project Management Association (IPMA). In collaboration with the National
         Technical University of Athens and Democritus University of Thrace
         ' 
  logo: 'ipma.png'
- icon: 'University-logo.png'
  name: 'Auth'
  details: '2004-2011'
  text: '<strong>Diploma of Rural and Surveying Engineering</strong> (Bac +5), Aristotle University of Thessaloniki, Greece, 
        Faculty of Engineering, School of Rural and Surveying Engineering (SRSE), Department of Geodesy and Surveying. 
        Rural and Surveying Engineering is a broad, multidisciplinary field of geosciences and applied engineering.
        The official duration of the program of studies is 10 semesters 300 ECTS'
  logo: 'auth.jpg'